version: '3.7'

services:

  mysql:
    container_name: mysql-flask
    image: mysql:latest
    restart: unless-stopped
    labels:
      project: flaskapp
      day: "22 March 2023"
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD="suasenha"
      - MYSQL_DATABASE="nomedobanco"
      - MYSQL_USER="usuario"
      - MYSQL_PASSWORD="banana"

volumes:
  mysql-data:
    name: mysql-data

networks:
  my-sql-python-app-network:
    name: my-sql-python-app-network
